#!/bin/bash
# ---------------------------------------------------------------------------
# Mail out of the container (PHP mail() -> sendmail -> SMTP).
#
# The php:*-apache base image ships NO MTA, but php.ini's sendmail_path still
# points at /usr/sbin/sendmail. Anything calling mail() therefore fails with
# "Unable to send mail: Unknown error" — which is what the 2FA-by-email login
# (melisplatform/melis-login-2fa-email) hits, locking you out of the BO.
#
# The image installs msmtp-mta, which PROVIDES /usr/sbin/sendmail as a thin SMTP
# client. This writes its config from the SMTP_* env vars. Defaults point at the
# stack's `mail` service (mailpit): nothing leaves your machine, and every message
# — 2FA codes included — is readable at http://localhost:${MAILPIT_PORT}.
# Point SMTP_HOST/SMTP_PORT/SMTP_USER/SMTP_PASSWORD/SMTP_TLS at a real relay to
# send for real — any SMTP server: a company mail host, a transactional provider,
# another container, or an MTA on the host (host.docker.internal). SMTP_TLS takes
# on|starttls (587), smtps (465, implicit TLS) or off (plaintext, LAN/dev only).
#
# Run as root from entrypoint.sh, before Apache starts.
# ---------------------------------------------------------------------------
set -u

SMTP_HOST="${SMTP_HOST:-}"
[ -z "$SMTP_HOST" ] && { echo "[melis-docker-react] Mail: SMTP_HOST empty — mail() left unconfigured."; exit 0; }

command -v msmtp >/dev/null 2>&1 || {
  echo "[melis-docker-react] Mail: msmtp not in this image (built before the mail support was added?) — rebuild with: docker compose up -d --build php"
  exit 0
}

SMTP_PORT="${SMTP_PORT:-1025}"
SMTP_TLS="${SMTP_TLS:-off}"
SMTP_FROM="${SMTP_FROM:-melis@localhost}"
# Rewrite the From: HEADER to SMTP_FROM, not just the envelope. Defaults to on as
# soon as we authenticate: a relay like Gmail only accepts mail whose sender is the
# authenticated account, and Melis sends as noreply@<its own domain> — Gmail then
# either rejects it or silently rewrites it. Set SMTP_FORCE_FROM=off to keep Melis'
# own From: (correct for a relay that allows arbitrary senders, e.g. Mailgun with a
# verified domain).
SMTP_FORCE_FROM="${SMTP_FORCE_FROM:-${SMTP_USER:+on}}"

{
  echo "# Generated by /melis-conf/mail-setup.sh on every boot — edits are lost."
  echo "defaults"
  # "-" = the calling process's stdout, which Apache already captures into
  # `docker compose logs`. A literal /dev/stderr path fails here: msmtp runs as
  # www-data and opening root's fd 2 is EACCES ("cannot log to /dev/stderr").
  echo "logfile -"
  echo ""
  echo "account default"
  echo "host ${SMTP_HOST}"
  echo "port ${SMTP_PORT}"
  echo "from ${SMTP_FROM}"
  case "$SMTP_TLS" in
    # Implicit TLS ("SMTPS"): the session is encrypted from the first byte, so
    # STARTTLS must be OFF or msmtp sends the command into an already-encrypted
    # channel and the handshake fails. Port 465 implies this even if TLS was just
    # set to "on" — that is the near-universal convention and getting it wrong is
    # the classic "cannot use TLS" on a relay that works everywhere else.
    smtps|implicit|465)
      echo "tls on"
      echo "tls_starttls off"
      echo "tls_trust_file /etc/ssl/certs/ca-certificates.crt" ;;
    on|1|starttls)
      echo "tls on"
      if [ "$SMTP_PORT" = "465" ]; then echo "tls_starttls off"; else echo "tls_starttls on"; fi
      echo "tls_trust_file /etc/ssl/certs/ca-certificates.crt" ;;
    *)
      echo "tls off" ;;
  esac
  if [ "$SMTP_FORCE_FROM" = "on" ] || [ "$SMTP_FORCE_FROM" = "1" ]; then
    echo "set_from_header on"
  fi
  if [ -n "${SMTP_USER:-}" ]; then
    echo "auth on"
    echo "user ${SMTP_USER}"
    echo "password ${SMTP_PASSWORD:-}"
  else
    echo "auth off"
  fi
} > /etc/msmtprc

# msmtp refuses a config other users can read (it may hold a password), and Apache
# runs it as www-data — so make it root-owned 0644 when there is no password, 0640
# with www-data as group when there is.
if [ -n "${SMTP_PASSWORD:-}" ]; then
  chown root:www-data /etc/msmtprc && chmod 640 /etc/msmtprc
else
  chown root:root /etc/msmtprc && chmod 644 /etc/msmtprc
fi

echo "[melis-docker-react] Mail: sendmail -> msmtp -> ${SMTP_HOST}:${SMTP_PORT} (from ${SMTP_FROM}${SMTP_USER:+, auth as ${SMTP_USER}})."
